name: gear_up
description: "Gear Up Automotive Ecosystem"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_cache_manager: ^3.3.2 # 🔥 ضفنا مكتبة مسح الكاش هنا 🔥

  # --- State Management (إدارة الحالة) ---
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^7.6.4

  # --- Networking (الاتصال بالنت والذكاء الاصطناعي) ---
  dio: ^5.3.3
  google_generative_ai: ^0.4.4

  # --- Database (قواعد البيانات) ---
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.5.4

  # --- UI (التصميم) ---
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.4
  percent_indicator: ^4.2.3

  # --- Maps & Location (الخرائط والموقع) ---
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # --- Utilities (أدوات مساعدة) ---
  intl: ^0.20.2
  uuid: ^4.2.1
  image_picker: ^1.2.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  cloudinary_public: ^0.23.1
  url_launcher: ^6.2.4
  share_plus: ^12.0.1
  webview_flutter: ^4.8.0
  mailer: ^6.1.1
  video_player: ^2.11.0

  # --- Notifications ---
  firebase_messaging: ^16.1.2
  flutter_local_notifications: ^17.1.2

  # 🔥 التعديلات الجديدة هنا (الإشعارات والجولة التعريفية) 🔥
  permission_handler: ^11.3.1
  showcaseview: ^5.0.1

  # 🔥 الباكدج الخاصة بالسبلاش سكرين
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 🔥 أسلحة الدمار الشامل (مكتبات التيست) 🔥
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.3

  flutter_lints: ^6.0.0

  # 🔥 الباكدج الخاصة بأيقونة التطبيق
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/sounds/

# ===================================================
# 🔥 إعدادات أيقونة التطبيق (App Icon) 🔥
# ===================================================
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/gear_up.png"
  remove_alpha_ios: true # 🔥 ضفنا السطر ده عشان أبل بترفض الأيقونات الشفافة 🔥
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/gear_up.png"

# ===================================================
# 🔥 إعدادات السبلاش سكرين (Splash Screen) 🔥
# ===================================================
flutter_native_splash:
  color: "#0A0F14"
  image: "assets/images/gear_up.png"
  android: true
  ios: true