import 'package:flutter/material.dart';

class AppLang {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      "continue_with_google": "Continue with Google",
      "or_sign_up_with_email": "Or sign up with email",
      "tour_search_title": "Quick Search",
      "tour_search_desc": "Search for any car or spare part here with one tap.",
      "tour_filter_title": "Smart Filter",
      "tour_filter_desc": "Filter results by brand, price, or condition to find exactly what you need.",
      "tour_saved_parts_title": "Saved Parts",
      "tour_saved_parts_desc": "Any spare part you save will appear here for quick access.",
      "tour_nearby_title": "Nearby Locations",
      "tour_nearby_desc": "Discover the nearest service centers, gas stations, and hospitals.",
      "tour_add_ad_title": "Sell Your Car Easily",
      "tour_add_ad_desc": "Tap here to post your car or spare parts ad to reach thousands of buyers.",
      "tour_saved_title": "Your Favorites",
      "tour_saved_desc": "Any car or part you save will be securely stored here.",
      "tour_card_save_title": "Save to Favorites",
      "tour_card_save_desc": "Tap the heart icon to save any car you like to view it later.",
      "tour_card_compare_title": "Smart Compare",
      "tour_card_compare_desc": "Tap the arrows to add this car to your comparison matrix.",
      "tour_ai_title": "Your AI Assistant",
      "tour_ai_desc": "Ask about any car or issue, and get instant smart answers.",
      "tour_compare_title": "Accurate Comparison",
      "tour_compare_desc": "Compare vehicles side-by-side to make the best choice.",
      "tour_parts_title": "Spare Parts",
      "tour_parts_desc": "Find compatible parts with transparent pricing.",
      "tour_mycar_title": "Digital Garage",
      "tour_mycar_desc": "Register your car to track maintenance and expenses easily.",
      "tour_body_title": "Offline-First Marketplace",
      "tour_body_desc": "Browse cars, compare specs accurately, and easily list your own car for sale. Designed to work flawlessly even with unstable internet.",
      "tour_nav_title": "Your Complete Ecosystem",
      "tour_nav_desc": "Manage your 'Digital Garage', track maintenance logs, find parts with transparent pricing, and locate trusted service centers all from here.",
      "clear_cache": "Clear Cache",
      "free_up_space": "Free up storage space",
      "cache_cleared": "Cache cleared successfully! ✨",
      "clear_cache_title": "Confirm Clear Cache",
      "clear_cache_desc": "Are you sure you want to clear the image and search cache? This will free up space on your phone. You will NOT be logged out of your account.",
      "cancel_btn": "Cancel",
      "confirm_clear": "Yes, Clear",
      "report": "Report",
      "like": "Like",
      "report_review": "Report Review",
      "confirm_report_review": "Does this comment contain offensive language or inappropriate content?\nIt will be sent to the admin for review.",
      "report_btn": "Report Comment",
      "review_reported_success": "Report sent to administration successfully.",
      "edit_btn": "Edit",
      "delete_btn": "Delete",
      "delete_review_btn": "Delete Comment",
      "is_info_correct": "Is the displayed information correct and accurate?",
      "no_error": "No, there is an error",
      "yes_correct": "Yes, correct",
      "report_success_msg": "Thank you for your contribution! The data will be reviewed by the administration.",
      "report_error_msg": "An error occurred while sending the report, please try again later.",
      "write_review": "Write a Review",
      "edit_review_title": "Edit Review",
      "share_experience": "Share your experience about this car...",
      "share_experience_part": "Share your opinion on this spare part...",
      "update_btn": "Update",
      "submit": "Submit",
      "no_text_comment": "No text provided",
      "gearup_user": "GEAR UP User",
      "login_required": "Login Required",
      "guest_sorry_prefix": "Sorry, you cannot",
      "guest_sorry_suffix": "as a guest. Log in to enjoy all GEAR UP features!",
      "like_comments": "like comments",
      "report_comments": "report comments",
      "save_ads": "save ads",
      "admin_privileges": "Admin Privileges",
      "delete_permanently_btn": "Delete Permanently",
      "admin_deleted_success": "Ad successfully deleted by admin",
      "share_car_content": "🚗 Check out this amazing car on Gear Up!",
      "share_part_content": "🔧 Check out this amazing spare part on Gear Up!",
      "my_car": "My Car",
      "add_car_to_garage": "Add Car to Garage",
      "add_your_cars": "Add",
      "view_all": "View All",
      "upcoming_reminders": "Upcoming Reminders",
      "no_upcoming_reminders": "No upcoming reminders currently",
      "maintenance_history": "Maintenance History",
      "no_maintenance_records": "No maintenance records for this car",
      "add_record": "Add Record",
      "year": "Year",
      "mileage": "Mileage",
      "days_overdue": "days overdue",
      "today": "Today",
      "days_left": "days left",
      "due_date": "Due Date:",
      "delete_record": "Delete Record",
      "delete_confirm_msg": "Are you sure you want to delete this record?",
      "record_deleted": "Record deleted successfully",
      "service_name": "Service Name",
      "cost_egp": "Cost (EGP)",
      "description_details": "Description / Details",
      "add_notes_here": "Add your notes here",
      "edit_record": "Edit Record",
      "save_changes": "Save Changes",
      "add_reminder": "Add Reminder",
      "edit_reminder": "Edit Reminder",
      "task": "Task",
      "notes_optional": "Notes (Optional)",
      "remove_from_compare": "Remove from compare",
      "added_to_comparison": "Add to comparison",
      "manage_reviews_reports": "Manage Reviews",
      "review_reported_comments_desc": "Review and delete comments containing offensive content",
      "reported_reviews_title": "Reported Reviews",
      "no_reported_reviews": "No pending reports!",
      "reported_reviews_count": "Reported Reviews",
      "share_part_text": "Check out this spare part: ",
      // --- Market Cubit (رسايل الإيرور والذكاء الاصطناعي) ---
      'err_login_first': 'You must login first',
      'err_max_compare': 'You can compare a maximum of 3 cars',
      'success_add_compare': 'Car added to comparison',
      'err_delete_ad_failed': 'Failed to delete the ad',
      'err_update_ad_failed': 'Failed to update the ad:',
      'ai_cancel_exit': 'Exited the screen',
      'ai_desc_default': 'A car with modern design and strong performance. For more details, please contact the seller.',
      'ai_desc_fetched': '✨ Specifications fetched via AI.',
      'ai_part_desc': '✨ Original spare part, price and specs fetched via AI.',
      'ai_personalized_desc': '✨ A car specially chosen for you based on your preferences.',
      'ai_filtered_desc': '✨ A car matching your search filters.',
      'not_available': 'N/A',
      'automatic': 'Automatic',
      'egypt': 'Egypt',
      'currency_egp': 'EGP',
      'average_price': 'Avg price',
      // --- Payment WebView ---
      'secure_payment_gateway': 'Secure Payment Gateway',
      'english_numbers_warning': 'Notice: Please enter numbers (OTP / PIN) in English format only (123...) to avoid transaction failure.',
      'connecting_to_bank': 'Connecting to the bank, please wait...',
      'page_load_failed': 'Failed to load page:',
      'retry_btn': 'Retry',
      // --- Paymob Errors ---
      'paymob_auth_error': 'Error: Paymob Authentication Failed (API Key)',
      'paymob_order_error': 'Error: Failed to create Order',
      'paymob_card_key_error': 'Error: Failed to issue Card Payment Key',
      'paymob_unexpected_error': 'Unexpected Error:',
      'paymob_auth_error_wallet': 'Error: Paymob Authentication Failed',
      'paymob_wallet_key_error': 'Error: Failed to issue Wallet Payment Key',
      'paymob_bank_reject_wallet': 'Bank did not send a payment link (Invalid Wallet Number)',
      'paymob_wallet_rejected_network': 'Wallet number rejected by the network',
      'login': 'Login',
      'verify_email_title': 'Verify Your Email',
      'verify_email_sent_to': 'We have sent a verification link to:\n',
      'verify_email_instructions': '\n\nPlease check your inbox and click the link to activate your account.',
      'waiting_for_verification': 'Waiting for verification...',
      'resend_link': 'Resend Link',
      'link_resent_success': 'Verification link resent successfully',
      'wait_before_resending': 'Please wait a moment before resending',
      'km': 'km',
      // --- Guest Dialog ---

      // Feature names inside the dialog
      'view_saved_cars': 'view saved cars',
      'view_saved_parts': 'view saved parts',
      'publish_ads_feature': 'publish ads',
      'manage_ads_feature': 'manage your ads',
      'manage_reviews_feature': 'manage reviews',
      'login_to_view_saved_parts': 'Please log in to view saved parts',
      // My Reviews (Empty State)
      'no_reviews_title': 'No Reviews Found',
      'no_reviews_desc': 'You haven\'t added any car reviews yet.',

// Admin Dashboard
      'control_panel': 'Dashboard',
      'overview': 'Overview',
      'users_count': 'Users',
      'active_cars_count': 'Active Cars',
      'spare_parts_count': 'Spare Parts',
      'pending_reports_count': 'Pending Reports',
      'platform_management': 'Platform Management',
      'manage_reports_btn': 'Manage Reports',
      'review_reported_cars': 'Review and delete reported cars',

// Pending Reports
      'pending_reports_title': 'Pending Reports',
      'status_pending': 'Pending',
      'click_to_view_ad': 'Click here to view ad details',
      'seller_label': 'Seller',
      'year_label': 'Year',
      'delete_ad_btn': 'Delete Ad',

// Change Password
      'change_password_title': 'Change Password',
      'change_password_desc': 'Update your password to increase your account security',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'update_password_btn': 'Update Password',

// Payment Methods
      'payment_methods_tab': 'Payment Methods',
      'history_tab': 'History',
      'no_saved_payment_methods': 'No saved payment methods',
      'add_payment_method_btn': 'Add Payment Method',
      'no_previous_transactions': 'No previous transactions',

// Add Payment Method Types
      'select_payment_type': 'Select Payment Type',
      'bank_card_option': 'Bank Card (Credit/Debit)',
      'mobile_wallet_option': 'Mobile Wallet ',

// Add E-Wallet
      'add_ewallet_title': 'Add E-Wallet',
      'wallet_number': 'Wallet Number',
      'english_numbers_hint': 'English numbers ',
      'name_label': 'Name',
      'save_btn': 'Save',

// Add New Card
      'add_new_card_title': 'Add New Card',
      'card_number': 'Card Number',
      'name_on_card': 'Name on Card',
      'full_name_hint': 'Full Name',
      'expiry_date': 'Expiry Date',
      'cvv_label': 'CVV',
      'three_digits_hint': '3 digits',

// Ad Publishing Fees
      'ad_publishing_fees_title': 'Ad Publishing Fees',
      'ad_publishing_fees_desc': 'To ensure the seriousness of the ads, a fee of 50 EGP will be deducted. Please select a payment method in the next step.',
      'agree_to_continue_btn': 'Agree to Continue',
      // Empty States
      'favorite_parts_empty': 'Your favorite spare parts will appear here',
      'no_cars_added_yet': 'You haven\'t added any cars yet',
      'no_part_description': 'No description available for this part.',

// Admin Privileges
      'admin_dashboard': 'Admin Dashboard',
      'admin_dashboard_desc': 'Statistics, users, and reports',

// Edit Car Details
      'edit_car_details_title': 'Edit Car Details',
      'edit_car_details_subtitle': 'Edit the necessary details and press save',
      'save_changes_btn': 'Save Changes',

// Validation / Reports

// Sorting
      'sort_default': 'Default',
      'sort_lowest_price': 'Lowest Price',
      'sort_highest_price': 'Highest Price',

// Reviews
      'my_reviews': 'My Reviews',
      'manage_previous_reviews': 'Manage your previous car reviews',
      // Personalized Cars Section (Home Screen)
      'personalized_cars_title': 'Cars For You',
      'based_on_prefs': 'Based on your preferences:',
      'view_more': 'View More',
      // شاشة ميزة سيارتي (Pop-up)
      'my_car_feature_title': 'My Car Feature',
      'my_car_feature_desc': 'Since you own a car, we added it to your profile! You can log its data, track maintenance, and easily set license renewal reminders.',
      'start_now': 'Start Now',

// للكلمات اللي ظهرت في الصور التانية (تأكيد على اللي فات)
      'welcome_to_gear_up': 'Welcome to GEAR UP',
      'skip': 'Skip',
      'q1_title': 'Do you currently own a car?',
      // General Buttons & Alerts
      'enter_app': 'Enter App',

// Welcome Screen
      'welcome_to': 'Welcome to',
      'gear_up': 'GEAR UP',
      'app_subtitle': 'The first car app powered by AI',
      'feature_1': 'Smart assistant for your inquiries',
      'feature_2': 'Tailored car recommendations for you',
      'feature_3': 'Accurate price and spec analysis',
      'start_customization': 'Let\'s Start',

// Question 1
      'question_1': 'First Question',
      'q1_ans_yes': 'Yes, I own a car',
      'q1_ans_no': 'No, I\'m looking for one',

// Question 2
      'question_2': 'Second Question',
      'q2_title': 'What is the main purpose of the car?',
      'q2_ans_family': 'Family & Comfort',
      'q2_ans_economy': 'Economy & Daily Work',
      'q2_ans_sport': 'Youth & Sporty',
      'q2_ans_luxury': 'Luxury & Premium',

// Last Question
      'question_last': 'Last Question',
      'q3_title': 'What is your approximate budget?',
      'q3_ans_1': 'Less than 500K EGP',
      'q3_ans_2': '500K to 1 Million EGP',
      'q3_ans_3': '1 to 2 Million EGP',
      'q3_ans_4': 'More than 2 Million EGP',

// Final Screen
      'customizing_ai': 'Customizing the app for you using AI...',
      'ready_to_go': 'Ready to go! 🚀',
      'prefs_saved_desc': 'Preferences saved successfully! You will now see cars tailored exactly to your needs on the home page.',

// My Car Feature (Tutorial)
      'welcome_title': 'Welcome to GEAR UP',
      'welcome_subtitle': 'The first car app powered by Artificial Intelligence',
      'start_customization_btn': 'Let\'s start customizing',
      "saved_parts": "Saved Parts",
      "compatibility": "Compatibility",
      "fits": "Fits:",
      "type_part": "Spare Part",
      "search_in": "Search in",
      "no_rated_cars_yet": "No rated cars yet",
      "no_matching_cars_found": "No matching cars found",
      "no_news_available": "No news available",
      "recent_searches": "Recent Searches",
      "start_searching": "Search for your favorite car now...",
      'top_rated_badge': 'Top Rated',
      'no_reviews_yet': 'No reviews yet. Be the first to review!',
      'search_cars': 'Search for cars...',
      "apply_filters": "Apply Filters",
      "clear_all": "Clear All",
      "filtered_results": "Filtered Results",
      "clear_filter": "Clear Filter",
      "brands": "BRANDS",
      "max_price": "MAX PRICE",
      "all_brands": "All Brands",
      "up_to": "Up to",
      "curated_for_you": "Curated For You",
      "randomly_selected_for_you": "Randomly selected specially for you",
      "latest_cars_news": "Latest Cars News",
      "news_insights": "News & Insights",
      "no_news_to_show": "No news available at the moment",
      "explore_premium_selection": "Explore our premium selection",
      "click_to_read_more": "Click to read full details...",
      "chat_history": "Chat History",
      "new_chat": "New Chat",
      "no_previous_chats": "No previous conversations",
      "rename_chat": "Rename Chat",
      "copy_chat": "Copy Chat",
      "share_chat": "Share Chat",
      "delete_chat": "Delete Chat",
      "edit": "Edit",
      "ai_thinking": "AI is thinking...",
      "always_here_to_help": "Always here to help",
      "rename_chat_title": "Rename Conversation",
      "type_new_name": "Type the new name...",
      "cancel": "Cancel",
      "save": "Save",
      "delete_confirmation_title": "Confirm Deletion",
      "delete_confirmation_desc": "Are you sure you want to permanently delete this conversation?",
      "yes_delete": "Yes, Delete",
      "chat_deleted_success": "Conversation deleted successfully",
      "chat_copied_success": "Conversation copied successfully!",
      "share_header": "🤖 Conversation from GEAR UP AI:\n\n",
      "you": "👤 You",
      "assistant": "🤖 Assistant",
      'connection_error': 'Connection error. Please check your internet connection.',
      'start_ad_now': 'Start Selling Now',
      'no_parts_to_show': 'No parts to display at the moment',
      'recently_added': 'Recently Added',
      'promoted_parts': 'Promoted Parts',
      'seller_location_title': 'Showroom Location',
      'open_in_maps': 'Open in Google Maps',
      'seller_info': 'Seller Information',
      'seller_name': 'Seller Name (Optional)',
      'seller_phone': 'Phone Number (Required)',
      'seller_email': 'Email (Optional)',
      'seller_location': 'Showroom Location (Optional)',
      'phone_required_error': 'Phone number is required to publish',
      'top_rated_cars': 'Top Rated Cars',
      'no_cars_to_show': 'No cars to display at the moment',
      'new_user': 'New User',
      'fetching_location': 'Fetching location...',
      'version': 'GEAR UP Version 2.0.0',
      'copyright': '© 2026 GEAR UP. All rights reserved.',

      // ================= Start Selling =================
      'start_selling_title': 'Start Selling',
      'choose_item_type': 'Choose item type and add details',
      'change': 'Change',
      'photos': 'Photos',
      'add_photo': 'Add Photo',
      'photo_hint': '0/10 photos - Add clear photos from different angles',
      'photo_limit_hint': 'You can add up to 10 photos for the car (Optional)',
      'title': 'Title',
      'title_hint': 'Enter an attractive title',
      'price_egp': 'Price (EGP)',
      'price_hint': 'Enter price',
      'transmission_hint': 'Select type',
      'part_name': 'Part/Accessory Name',
      'part_hint': 'e.g., Ceramic Brake Pads',
      'compat_hint': 'e.g., BMW X5 2020-2024',
      'condition': 'Condition',
      'condition_hint': 'Select condition',
      'description': 'Description',
      'desc_hint': 'Add a detailed description...',
      'desc_optional_hint': 'Write a description for the car (Optional)',
      'publish_listing': 'Publish Listing',
      'select_item_type': 'Select Item Type',
      'type_car': 'Car',
      'type_accessory': 'Accessory',
      'manual': 'Manual',
      'new_condition': 'New',
      'used_condition': 'Used',
      'refurbished': 'Refurbished',
      'company_hint': 'e.g., BMW',
      'model_hint': 'e.g., X5',
      'year_optional_hint': '2024 (Optional)',
      'mileage_optional_hint': 'km (Optional)',
      'hp_optional_hint': '335 (Optional)',
      'cc_optional_hint': '3000 (Optional)',
      'torque_optional_hint': '330 (Optional)',
      'luggage_optional_hint': '650 L (Optional)',
      'price_make_required': 'Price and Company are required at least',
      'not_specified': 'Not specified',
      'publish_success': 'Listing published successfully!',
      'coming_soon_parts': 'Adding parts will be enabled soon',

      // ================= Privacy Policy =================
      'privacy_policy_title': 'Privacy Policy',
      'last_updated': 'Last updated: October 23, 2025',
      'pp_sec1_title': '1. Information We Collect',
      'pp_sec1_p1': 'GEAR UP collects information that you provide directly to us when you create an account, use our services, or communicate with us. This may include your name, email address, phone number, and vehicle information.',
      'pp_sec1_p2': 'We also automatically collect certain information about your device and how you interact with our app, including your IP address, device type, operating system, and usage patterns.',
      'pp_sec2_title': '2. How We Use Your Information',
      'pp_sec2_p1': 'We use the information we collect to:',
      'pp_sec2_b1': 'Provide, maintain, and improve our services',
      'pp_sec2_b2': 'Send you technical notices and support messages',
      'pp_sec2_b3': 'Respond to your comments and questions',
      'pp_sec2_b4': 'Provide personalized car recommendations',
      'pp_sec2_b5': 'Monitor and analyze trends, usage, and activities',
      'pp_sec2_b6': 'Detect, prevent, and address technical issues',
      'pp_sec3_title': '3. Information Sharing',
      'pp_sec3_p1': 'We do not sell your personal information. We may share your information only in the following circumstances: with your consent, with service providers who help us operate our business, to comply with legal obligations, or to protect our rights and safety.',
      'pp_sec4_title': '4. Data Security',
      'pp_sec4_p1': 'We take reasonable measures to help protect your personal information from loss, theft, misuse, unauthorized access, disclosure, alteration, and destruction. However, no internet transmission is ever fully secure or error-free.',
      'pp_sec5_title': '5. Your Rights and Choices',
      'pp_sec5_p1': 'You have the right to:',
      'pp_sec5_b1': 'Access and update your account information',
      'pp_sec5_b2': 'Request deletion of your personal data',
      'pp_sec5_b3': 'Opt-out of marketing communications',
      'pp_sec5_b4': 'Disable cookies through your browser settings',
      'pp_sec6_title': '6. Children\'s Privacy',
      'pp_sec6_p1': 'Our services are not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that a child has provided us with personal information, please contact us.',
      'pp_sec7_title': '7. Changes to This Policy',
      'pp_sec7_p1': 'We may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page and updating the "Last updated" date.',
      'pp_sec8_title': '8. Contact Us',
      'pp_sec8_p1': 'If you have any questions about this Privacy Policy, please contact us at:\nEmail: privacy@gearup.com\nPhone: +20 2 1234 5678',

      // ================= Profile Screen =================
      'my_account': 'My Account',
      'start_selling': 'Start Selling',
      'list_new_item': 'List a new item',
      'published_items': 'Published Items',
      'manage_listings': 'Manage your listings',
      'account_info_sub': 'Name, email, phone',
      'edit_profile_sub': 'Update your information',
      'manage_payment_methods': 'Manage Payment Methods',
      'app_section': 'App',
      'settings_sub': 'Preferences, Privacy, Help',
      'logout': 'Logout',
      'egypt_car_app': 'Egypt\'s #1 Car App',

      // ================= Published Items =================
      'tab_all': 'All',
      'tab_cars': 'Cars',
      'tab_parts': 'Parts',
      'tab_accessories': 'Accessories',
      'no_listings_yet': 'No listings yet',
      'haven_not_published': 'You haven\'t published any listings yet',

      // ================= Profile & Account =================
      'account_information': 'Account Information',
      'view_account_details': 'View your account details',
      'member_since': 'Member Since',
      'email_address': 'Email Address',
      'location': 'Location',
      'edit_information': 'Edit Information',
      'update_account_password': 'Update your account password',
      'update_password': 'Update Password',
      'edit_profile': 'Edit Profile',
      'change_profile_photo': 'Change Profile Photo',

      // ================= Nearby Locations =================
      'nearby_locations': 'Nearby Locations',
      'service_and_showrooms': 'Service centers & showrooms',
      'interactive_map': 'Interactive Map',
      'shows_places_near_you': 'Shows service centers & showrooms near you',
      'service_center': 'Service Center',
      'showroom': 'Showroom',
      'km_away': 'km away',
      'get_directions': 'Get Directions',

      // ================= Parts Screen =================
      'car_parts': 'Car Parts',
      'parts_available': 'parts available',
      'search_parts': 'Search parts...',
      'all_companies': 'All Companies',
      'default_sort': 'Default',

      // ================= General & Navigation =================
      'home': 'Home',
      'compare': 'Compare',
      'parts': 'Parts',
      'profile': 'Profile',
      'settings': 'Settings',
      'delete': 'Delete',
      'remove': 'Remove',
      'manage': 'Manage',

      // ================= Splash & Welcome =================
      'premium_companion': 'Your Premium Car Companion',
      'skip_to_home': 'Skip to Home',

      // ================= Auth Screens =================
      'welcome_back': 'Welcome Back',
      'sign_in': 'Sign in to continue',
      'forgot_password_title': 'Forgot Password?',
      'forgot_password_desc': 'Enter your email and we\'ll send you instructions to reset your password',
      'email': 'Email',
      'email_hint': 'your@email.com',
      'send_reset_link': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'password': 'Password',
      'password_hint': '••••••••',
      'or_continue_with': 'Or continue with',
      'google': 'Google',
      'facebook': 'Facebook',
      'dont_have_account': 'Don\'t have an account? ',
      'sign_up': 'Sign up',
      'create_account': 'Create Account',
      'join_gear_up': 'Join GEAR UP today',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'phone_hint': '+20 123 456 7890',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',

      // ================= Home & Search =================
      'popular_searches': 'POPULAR SEARCHES',
      'saved_cars': 'Saved Cars',
      'find_nearby': 'Find Nearby',
      'promoted': 'Promoted',
      'featured_listings': 'Featured Listings',
      'premium_listings': 'Premium featured listings',
      'top_rated_new': 'Top Rated New Cars',
      'best_rated_2025': 'Best rated vehicles in 2025',
      'latest_updates': 'Latest automotive updates',
      'new_cars': 'New Cars',
      'latest_models': 'Latest models from top brands',
      'used_cars': 'Used Cars',
      'quality_preowned': 'Quality pre-owned vehicles',

      // ================= Compare & Car Details =================
      'compare_vehicles': 'Compare Vehicles',
      'analyze_specs': 'Analyze side-by-side specifications',
      'specification': 'Specification',
      'company': 'Company',
      'model': 'Model',
      'transmission': 'Transmission',
      'hp': 'HP',
      'cc': 'CC',
      'torque': 'Torque',
      'luggage_capacity': 'Luggage Capacity',
      'gear_shifts': 'Gear Shifts',
      'max_speed': 'Max Speed',
      'comparison_guide': 'Comparison Guide',
      'indicates_advantage': 'Indicates advantage',
      'indicates_disadvantage': 'Indicates disadvantage',
      'specifications_title': 'Specifications',
      'about_vehicle': 'About this vehicle',
      'total_views': 'Total Views',
      'reviews': 'Reviews',
      'top_rated': 'Top Rated',
      'mock_desc': 'is a premium vehicle featuring a powerful 335 HP engine with 3000cc capacity. With its Automatic transmission and 8 gear shifts, this car delivers exceptional performance and efficiency. The vehicle can reach a maximum speed of 250 km/h and offers 650 L of luggage capacity, making it perfect for both daily commutes and long journeys.',

      // ================= My Car & Reminders =================
      'login_signup_msg': 'Log in or sign up to manage your vehicle, track maintenance history, and set reminders',
      'manage_vehicles': 'Manage your vehicles',
      'my_vehicle': 'My Vehicle',
      'service_centers': 'Service Centers',
      'parts_used_notes': 'Parts used, mechanic notes...',
      'edit_my_vehicle': 'Edit My Vehicle',
      'vehicle_details': 'Vehicle Details',
      'update_car_info': 'Update your car\'s information and mileage',
      'change_vehicle_photo': 'Change Vehicle Photo',
      'car_brand': 'Car Brand',
      'car_model': 'Car Model',
      'manufacturing_year': 'Manufacturing Year',
      'mileage_km': 'Mileage (km)',
      'manage_reminders': 'Manage your car maintenance reminders',
      'task_hint': 'e.g., Oil Change, Tire Rotation',
      'date_hint': 'mm/dd/yyyy',
      'additional_details': 'Additional details...',
      'delete_reminder': 'Delete Reminder',
      'reminder_deleted': 'Reminder deleted successfully!',

      // ================= AI Chat & Filters =================
      'ai_title': 'GEAR UP AI',
      'ai_subtitle': 'Always here to help',
      'ai_greeting': 'Hi! I\'m your GEAR UP AI assistant. How can I help you today?',
      'quick_suggestions': 'Quick suggestions:',
      'sugg_electric': 'Show me electric cars',
      'sugg_sedans': 'Compare sedans under 30k',
      'sugg_suvs': 'Best SUVs for families',
      'type_message': 'Type your message...',
      'filters': 'Filters',
      'price': 'Price',
      'high_to_low': 'High to Low',
      'low_to_high': 'Low to High',
      'under_500k': 'Under 500K',

      // ================= Settings Screen =================
      'manage_preferences': 'Manage your app preferences & support',
      'app_preferences': 'App Preferences',
      'dark_mode': 'Dark Mode',
      'dark_enabled': 'Dark theme enabled',
      'light_enabled': 'Light theme enabled',
      'push_notifications': 'Push Notifications',
      'receive_updates': 'Receive updates and reminders',
      'language': 'Language',
      'select_language': 'Select your preferred language',
      'security_privacy': 'Security & Privacy',
      'change_password': 'Change Password',
      'privacy_policy': 'Privacy Policy',
      'terms_privacy': 'Terms and privacy rules',
      'support_about': 'Support & About',
      'help_center': 'Help Center',
      'get_support': 'Get support & FAQ',
      'analytics': 'Analytics & Performance',
      'help_improve': 'Help improve the app',

      // ================= Help Center Screen =================
      'search_help': 'Search for help...',
      'chat_support': 'Chat Support',
      'call_us': 'Call Us',
      'email_us': 'Email Us',
      'user_guide': 'User Guide',
      'categories': 'Categories',
      'all': 'All',
      'general': 'General',
      'features': 'Features',
      'service': 'Service',
      'faq': 'Frequently Asked Questions',
      'still_need_help': 'Still need help?',
      'phone': 'Phone',
      'faq_q1': 'How do I search for a car?',
      'faq_a1': 'You can search for cars by browsing the Home screen or using the Search bar at the top.',
      'faq_q2': 'How do I save a car to my favorites?',
      'faq_a2': 'Tap the heart icon on any car card to save it to your Saved Cars list.',
      'faq_q3': 'How does the comparison feature work?',
      'faq_a3': 'Select up to 2 cars by tapping the compare icon, then go to the Compare tab to see them side-by-side.',
      'faq_q4': 'Can I track my car maintenance?',
      'faq_a4': 'Yes! Go to your Profile, then "My Car" to add and track your maintenance history.',
      'faq_q5': 'How do I find car parts?',
      'faq_a5': 'Visit the Parts tab to browse or search for specific car parts.',
      'faq_q6': 'How do I reset my password?',
      'faq_a6': 'On the login screen, tap "Forgot Password?" to receive a reset link.',
      'faq_q7': 'Where can I find service centers near me?',
      'faq_a7': 'Go to the Home screen and tap "Find Nearby" to see a map of service centers.',
      'faq_q8': 'How do I enable dark mode?',
      'faq_a8': 'Navigate to Settings from your Profile and toggle the Dark Mode switch.',
      'faq_q9': 'What is the AI Chat Agent?',
      'faq_a9': 'The AI Chat Agent is your virtual assistant. Tap the floating icon to ask questions.',
      'faq_q10': 'How do I change my profile information?',
      'faq_a10': 'Go to your Profile page and tap "Edit Information".',

      // ================= Payments Screen =================
      'payments': 'Payments',
      'manage_payments': 'Manage Payments',
      'payment_methods': 'Payment Methods',
      'history': 'History',
      'add_payment_method': 'Add Payment Method',
      'default_method': 'Default',
      'select_payment_method': 'Select Payment Method',
      'credit_debit_card': 'Credit / Debit Card',
      'add_card': 'Add Card',
      'add_instapay': 'Add InstaPay',
      'add_vodafone_cash': 'Add Vodafone Cash',
      'cardholder_name': 'Cardholder Name',
      'cvv': 'CVV',
      "tour_start_ad_title": "Start Your Ad",
      "tour_start_ad_desc": "Click here to publish your car ad and reach thousands of buyers.",
      "tour_my_car_title": "Your Digital Garage",
      "tour_my_car_desc": "Track your car's maintenance and expenses.",
      "tour_profile_title": "Your Profile",
      "tour_profile_desc": "All your settings and ads are here.",
      "or_login_with_email": "Or login with email",
      "siren_channel_desc": "Channel for maintenance alerts with siren sound",
      "nav_home": "Home",
      "nav_compare": "Compare",
      "nav_parts": "Parts",
      "nav_my_car": "My Car",
      "nav_profile": "Profile",
      "no_cars_to_compare": "No cars to compare",
      "add_cars_from_home": "Add cars from the home screen",
      "new": "New",
      "used": "Used",
      'name': 'Name',
      'completed': 'Completed',
      'pending': 'Pending',
      "sugg_title_1": "Latest Car News",
      "sugg_desc_1": "What's new in the car market?",
      "sugg_title_2": "Troubleshooting",
      "sugg_desc_2": "My car overheats quickly, what's the reason?",
      "sugg_title_3": "Buying Tips",
      "sugg_desc_3": "How to inspect a used car before buying?",
      "sugg_title_4": "Car Comparison",
      "sugg_desc_4": "Best family car under 1 million EGP?",
      "location_services_disabled": "Please enable location services (GPS)",
      "location_permission_denied": "Location permission denied",
      "location_permission_permanently_denied": "Location permission permanently denied from settings",
      "current_location": "Your current location",
      "cannot_open_maps": "Cannot open maps",
      "no_data_currently": "No data currently available",
      "km_label": "km",
      "meter_label": "m",
          "open_mail_app": "Open Email App",
  "check_spam_hint": "If you can't find the email, check your Spam/Junk folder",
  "no_email_app": "No email app found on your phone.",
  "choose_email_app": "Choose Mail App"
    },
    'ar': {
      "tour_search_title": "بحث سريع",
      "tour_search_desc": "ابحث عن أي سيارة أو قطعة غيار من هنا بضغطة واحدة.",
      "tour_filter_title": "فلتر النتائج",
      "tour_filter_desc": "فلتر النتائج براحتك (ماركة، سعر، حالة) عشان توصل للي بتدور عليه بالظبط.",
      "tour_saved_parts_title": "القطع المحفوظة",
      "tour_saved_parts_desc": "أي قطعة غيار تنال إعجابك وتقوم بحفظها ستجدها هنا.",
      "tour_nearby_title": "الأماكن القريبة",
      "tour_nearby_desc": "اكتشف أقرب مراكز الصيانة، محطات الوقود، والمستشفيات حولك.",
      "tour_add_ad_title": "بيع سيارتك بسهولة",
      "tour_add_ad_desc": "اضغط هنا لرفع إعلان سيارتك أو قطع الغيار لتصل لآلاف المشترين.",
      "tour_saved_title": "مفضلاتك في أمان",
      "tour_saved_desc": "أي سيارة أو قطعة غيار تحفظها، ستجدها مجمعة هنا للوصول السريع.",
      "tour_card_save_title": "حفظ للإعجاب",
      "tour_card_save_desc": "اضغط على علامة القلب لحفظ أي سيارة تنال إعجابك للرجوع إليها لاحقاً.",
      "tour_card_compare_title": "مقارنة ذكية",
      "tour_card_compare_desc": "اضغط على سهمي المقارنة لإضافة السيارة لجدول المقارنة مع سيارات أخرى.",
      "tour_ai_title": "مساعدك الشخصي",
      "tour_ai_desc": "اسأل الذكاء الاصطناعي عن أي سيارة أو عطل وسيجيبك فوراً.",
      "tour_compare_title": "مقارنة دقيقة",
      "tour_compare_desc": "قارن بين سيارتين لتعرف الأفضل لك بالأرقام والمواصفات.",
      "tour_parts_title": "قطع الغيار",
      "tour_parts_desc": "ابحث عن قطع غيار متوافقة مع سيارتك بأسعار عادلة.",
      "tour_mycar_title": "جراجك الرقمي",
      "tour_mycar_desc": "سجل سيارتك هنا وتابع مواعيد الصيانة ومصاريفك بسهولة.",
      "tour_body_title": "سوق متكامل يعمل بدون إنترنت",
      "tour_body_desc": "تصفح السيارات، قارن المواصفات بدقة، واعرض سيارتك للبيع بكل سهولة. النظام مصمم ليعمل بكفاءة حتى في أضعف حالات الاتصال بالإنترنت.",
      "tour_nav_title": "نظامك البيئي الشامل",
      "tour_nav_desc": "من هنا يمكنك إدارة 'جراجك الرقمي'، تتبع مواعيد الصيانة، والبحث عن قطع الغيار بأسعار عادلة وشفافة، بالإضافة للوصول لأقرب مراكز الخدمة.",
      "clear_cache": "مسح الذاكرة المؤقتة",
      "free_up_space": "تفريغ مساحة التخزين",
      "cache_cleared": "تم مسح الذاكرة المؤقتة بنجاح! ✨",
      "clear_cache_title": "تأكيد مسح الذاكرة",
      "clear_cache_desc": "هل أنت متأكد من مسح الذاكرة المؤقتة للصور والبحث؟ سيؤدي هذا لتوفير مساحة بهاتفك، ولن يتم تسجيل خروجك من حسابك.",
      "cancel_btn": "إلغاء",
      "confirm_clear": "نعم، امسح",
      "report": "إبلاغ",
      "like": "إعجاب",
      "report_review": "إبلاغ عن تعليق",
      "confirm_report_review": "هل يحتوي هذا التعليق على ألفاظ مسيئة أو محتوى غير لائق؟\nسيتم إرساله للإدارة لمراجعته وحذفه.",
      "report_btn": "إبلاغ عن التعليق",
      "review_reported_success": "تم إرسال البلاغ للإدارة بنجاح.",
      "edit_btn": "تعديل",
      "delete_btn": "مسح",
      "delete_review_btn": "مسح التعليق",
      "is_info_correct": "هل هذه المعلومات المعروضة سليمة ودقيقة؟",
      "no_error": "لا، يوجد خطأ",
      "yes_correct": "نعم، صحيحة",
      "report_success_msg": "شكراً لمساهمتك! سيتم مراجعة البيانات من قبل الإدارة.",
      "report_error_msg": "حدث خطأ أثناء إرسال الملاحظة، يرجى المحاولة لاحقاً.",
      "write_review": "اكتب تقييماً",
      "edit_review_title": "تعديل التقييم",
      "share_experience": "شارك تجربتك عن هذه السيارة...",
      "share_experience_part": "شارك رأيك في قطعة الغيار هذه...",
      "update_btn": "تحديث",
      "submit": "إرسال",
      "no_text_comment": "بدون نص",
      "gearup_user": "مستخدم GEAR UP",
      "login_required": "تسجيل الدخول مطلوب",
      "guest_sorry_prefix": "عفواً، لا يمكنك",
      "guest_sorry_suffix": "كزائر. قم بتسجيل الدخول لتستمتع بجميع مميزات GEAR UP!",
      "like_comments": "الإعجاب بالتعليقات",
      "report_comments": "الإبلاغ عن التعليقات",
      "save_ads": "حفظ الإعلانات",
      "admin_privileges": "صلاحيات الإدارة (Admin)",
      "delete_permanently_btn": "مسح نهائي",
      "admin_deleted_success": "تم مسح الإعلان بنجاح بواسطة الإدارة",
      "share_car_content": "🚗 ألقِ نظرة على هذه السيارة المميزة على Gear Up!",
      "share_part_content": "🔧 ألقِ نظرة على قطعة الغيار المميزة على Gear Up!",
      "my_car": "سيارتي",
      "add_car_to_garage": "إضافة سيارة للجراج",
      "add_your_cars": "إضافة",
      "view_all": "عرض الكل",
      "upcoming_reminders": "التذكيرات القادمة",
      "no_upcoming_reminders": "لا توجد تذكيرات قادمة حالياً",
      "maintenance_history": "سجل الصيانة",
      "no_maintenance_records": "لا توجد سجلات صيانة لهذه السيارة",
      "add_record": "إضافة سجل",
      "year": "سنة الصنع",
      "mileage": "المسافة المقطوعة",
      "days_overdue": "أيام متأخرة",
      "today": "اليوم",
      "days_left": "أيام متبقية",
      "due_date": "تاريخ الاستحقاق:",
      "delete_record": "حذف السجل",
      "delete_confirm_msg": "هل أنت متأكد من حذف هذا السجل؟",
      "record_deleted": "تم حذف السجل بنجاح",
      "service_name": "اسم الخدمة",
      "cost_egp": "التكلفة (جنيه)",
      "description_details": "الوصف / التفاصيل",
      "add_notes_here": "أضف ملاحظاتك هنا",
      "edit_record": "تعديل السجل",
      "save_changes": "حفظ التغييرات",
      "add_reminder": "إضافة تذكير",
      "edit_reminder": "تعديل التذكير",
      "task": "المهمة",
      "notes_optional": "ملاحظات (اختياري)",
      'login_to_view_saved_cars': 'قم بتسجيل الدخول لعرض سياراتك المحفوظة',
      'login': 'تسجيل الدخول',
      'saved_cars': 'السيارات المحفوظة',
      'no_saved_cars': 'لم تقم بحفظ أي سيارات بعد',
      'favorite_cars_appear_here': 'سياراتك المفضلة ستظهر هنا',
      'personalized_cars_title': 'العربيات المصممة لك',
      // --- Market Cubit (رسايل الإيرور والذكاء الاصطناعي) ---
      'err_login_first': 'يجب تسجيل الدخول أولاً',
      'err_max_compare': 'يمكنك مقارنة 3 سيارات كحد أقصى',
      'success_add_compare': 'تم إضافة السيارة للمقارنة',
      'err_delete_ad_failed': 'فشل مسح الإعلان',
      'err_update_ad_failed': 'فشل تحديث الإعلان:',
      'ai_cancel_exit': 'تم الخروج من الشاشة',
      'ai_desc_default': 'سيارة بتصميم عصري وأداء قوي. لمعاينة السيارة ومعرفة تفاصيل أكثر، يرجى التواصل مع البائع مباشرة.',
      'ai_desc_fetched': '✨ تم جلب المواصفات عبر الذكاء الاصطناعي.',
      'ai_part_desc': '✨ قطعة غيار أصلية، تم جلب السعر والمواصفات عبر الذكاء الاصطناعي.',
      'ai_personalized_desc': '✨ سيارة تم اختيارها خصيصاً لك بناءً على تفضيلاتك.',
      'ai_filtered_desc': '✨ سيارة متطابقة مع فلاتر البحث الخاصة بك.',
      'not_available': 'غير متوفر',
      'automatic': 'أوتوماتيك',
      'egypt': 'مصر',
      // --- حل مشاكل الكارت ---
      'currency_egp': 'ج.م',
      'cy_egp': 'ج.م', // ضفتها كاحتياطي لو الكود عندك معلق عليها
      'average_price': 'متوسط السعر',
      'Avg price': 'متوسط السعر', // لو الكلمة مكتوبة هارد كود

      // --- حل مشاكل تفضيلات المستخدم (الـ Subtitles الجاية من الفايربيز) ---
      'Youth & Sporty': 'بناءً على تفضيلاتك: شبابية ورياضية',
      'Family & Comfortable': 'بناءً على تفضيلاتك: عائلية ومريحة',
      'Economy & Daily': 'بناءً على تفضيلاتك: اقتصادية للعمل واليومي',
      'Luxury & Premium': 'بناءً على تفضيلاتك: فخامة ورفاهية',

      // والنسخ العربي عشان لو الداتا متسجلة بالعربي تترجم صح في الإنجليزي
      'عائلية ومريحة': 'بناءً على تفضيلاتك: عائلية ومريحة',
      'اقتصادية للعمل واليومي': 'بناءً على تفضيلاتك: اقتصادية للعمل واليومي',
      'شبابية ورياضية': 'بناءً على تفضيلاتك: شبابية ورياضية',
      'فخامة ورفاهية': 'بناءً على تفضيلاتك: فخامة ورفاهية',
      // --- Payment WebView ---
      'secure_payment_gateway': 'بوابة الدفع الآمنة',
      'english_numbers_warning': 'تنبيه: يرجى كتابة الأرقام (OTP / السرية) باللغة الإنجليزية فقط (123...) لتجنب فشل العملية.',
      'connecting_to_bank': 'جاري الاتصال بالبنك، يرجى الانتظار...',
      'page_load_failed': 'فشل في تحميل الصفحة:',
      'retry_btn': 'إعادة المحاولة',
      // --- Paymob Errors ---
      'paymob_auth_error': 'خطأ: فشل المصادقة مع بيموب (API Key)',
      'paymob_order_error': 'خطأ: فشل إنشاء الطلب (Order)',
      'paymob_card_key_error': 'خطأ: فشل إصدار مفتاح الدفع للفيزا',
      'paymob_unexpected_error': 'خطأ غير متوقع:',
      'paymob_auth_error_wallet': 'خطأ: فشل المصادقة مع بيموب',
      'paymob_wallet_key_error': 'خطأ: فشل إصدار مفتاح الدفع للمحفظة',
      'paymob_bank_reject_wallet': 'البنك لم يرسل رابط الدفع (الرقم غير صالح للمحفظة)',
      'paymob_wallet_rejected_network': 'رقم المحفظة مرفوض من شبكة فودافون/بيموب',
      'verify_email_title': 'تحقق من بريدك الإلكتروني',
      'verify_email_sent_to': 'لقد أرسلنا رابط التحقق إلى:\n',
      'verify_email_instructions': '\n\nيرجى فتح صندوق الوارد والضغط على الرابط لتفعيل حسابك.',
      'waiting_for_verification': 'في انتظار التحقق...',
      'resend_link': 'إعادة إرسال الرابط',
      'link_resent_success': 'تم إعادة إرسال الرابط بنجاح',
      'wait_before_resending': 'برجاء الانتظار قليلاً قبل إعادة الإرسال',
      'km': 'كم',
      // --- صندوق الزوار (Guest Dialog) ---

      // أسماء المميزات اللي بتظهر جوه الصندوق
      'view_saved_cars': 'عرض السيارات المحفوظة',
      'view_saved_parts': 'عرض قطع الغيار المحفوظة',
      'publish_ads_feature': 'نشر إعلانات',
      'manage_ads_feature': 'إدارة الإعلانات',
      'manage_reviews_feature': 'إدارة التقييمات',
      'login_to_view_saved_parts': 'قم بتسجيل الدخول لعرض قطع الغيار المحفوظة',
      // تقييماتي (الـ Empty State)
      'no_reviews_title': 'لا توجد تقييمات',
      'no_reviews_desc': 'لم تقم بإضافة أي تقييمات للسيارات حتى الآن.',

// لوحة تحكم الإدارة (Dashboard)
      'control_panel': 'لوحة التحكم',
      'overview': 'نظرة عامة',
      'users_count': 'المستخدمين',
      'active_cars_count': 'السيارات النشطة',
      'spare_parts_count': 'قطع الغيار',
      'pending_reports_count': 'البلاغات المعلقة',
      'platform_management': 'إدارة المنصة',
      'manage_reports_btn': 'إدارة البلاغات',
      'review_reported_cars': 'مراجعة السيارات المبلغ عنها وحذفها',

// البلاغات المعلقة
      'pending_reports_title': 'البلاغات المعلقة',
      'status_pending': 'معلق',
      'click_to_view_ad': 'اضغط هنا لعرض تفاصيل الإعلان',
      'seller_label': 'البائع',
      'year_label': 'السنة',
      'delete_ad_btn': 'حذف الإعلان',

// تغيير كلمة المرور
      'change_password_title': 'تغيير كلمة المرور',
      'change_password_desc': 'قم بتحديث كلمة المرور لزيادة أمان حسابك',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'update_password_btn': 'تحديث كلمة المرور',

// طرق الدفع (Payment Methods)
      'payment_methods_tab': 'طرق الدفع',
      'history_tab': 'السجل',
      'no_saved_payment_methods': 'لا توجد طرق دفع محفوظة',
      'add_payment_method_btn': 'إضافة طريقة دفع',
      'no_previous_transactions': 'لا توجد عمليات سابقة',

// إضافة طرق الدفع
      'select_payment_type': 'اختر نوع الدفع',
      'bank_card_option': 'بطاقة بنكية (Credit/Debit)',
      'mobile_wallet_option': 'موبايل واليت (فودافون، اتصالات، اورانج، وي)',

// إضافة محفظة إلكترونية
      'add_ewallet_title': 'إضافة محفظة إلكترونية',
      'wallet_number': 'رقم المحفظة',
      'english_numbers_hint': 'رقم إنجليزي (010, 011, 012, 015)',
      'name_label': 'الاسم',
      'save_btn': 'حفظ',

// إضافة بطاقة جديدة
      'add_new_card_title': 'إضافة بطاقة جديدة',
      'card_number': 'رقم البطاقة',
      'name_on_card': 'الاسم على البطاقة',
      'full_name_hint': 'الاسم بالكامل',
      'expiry_date': 'تاريخ الانتهاء',
      'cvv_label': 'CVV',
      'three_digits_hint': 'أرقام 3',

// رسوم نشر الإعلان
      'ad_publishing_fees_title': 'رسوم نشر الإعلان',
      'ad_publishing_fees_desc': 'لضمان جدية الإعلانات، سيتم خصم مبلغ 50 جنيهاً مصرياً. يرجى اختيار طريقة الدفع في الخطوة التالية.',
      'agree_to_continue_btn': 'موافق للمتابعة',
      // الشاشات الفارغة (Empty States)
      'favorite_parts_empty': 'قطع الغيار المفضلة لديك ستظهر هنا',
      'no_cars_added_yet': 'لم تقم بإضافة سيارات بعد',
      'no_part_description': 'لا يوجد وصف متاح لهذه القطعة.',

// صلاحيات الإدارة (Admin)
      'admin_dashboard': 'لوحة تحكم الإدارة',
      'admin_dashboard_desc': 'إحصائيات، مستخدمين، وبلاغات',

// تعديل بيانات السيارة
      'edit_car_details_title': 'تعديل بيانات السيارة',
      'edit_car_details_subtitle': 'عدل البيانات اللي محتاجها واضغط حفظ',
      'save_changes_btn': 'حفظ التعديلات',

// التأكد من صحة المعلومات (البلاغات)

// الفلاتر والترتيب (Sorting)
      'sort_default': 'الافتراضي',
      'sort_lowest_price': 'الأقل سعراً',
      'sort_highest_price': 'الأعلى سعراً',
      "compare_vehicles": "مقارنة السيارات",
      "no_cars_to_compare": "لا توجد سيارات للمقارنة",
      "add_cars_from_home": "قم بإضافة سيارات من الشاشة الرئيسية",
      "analyze_specs": "تحليل المواصفات جنباً إلى جنب",
      "remove": "إزالة",
      "cc": "سعة المحرك",
      "hp": "قوة الحصان",
      "torque": "عزم الدوران",
      "luggage_capacity": "الشنطة",
      "transmission": "ناقل الحركة",
      "condition": "الحالة",
      "new": "جديد",
      "used": "مستعمل",
      "manual": "مانيوال",

// التقييمات (Reviews)
      'my_reviews': 'تقييماتي',
      'manage_previous_reviews': 'إدارة تقييماتك السابقة للسيارات',
      // قسم العربيات المخصصة (الصفحة الرئيسية)
      'based_on_prefs': 'بناءً على تفضيلاتك:',
      'view_more': 'عرض المزيد', // لو حابب تعربها، أو سيبها 'View More' زي ما هي في التصميم
      // شاشة ميزة سيارتي (Pop-up)
      'my_car_feature_title': 'ميزة سيارتي (My Car)',
      'my_car_feature_desc': 'بما إنك تمتلك سيارة، ضفناها لك في ملفك الشخصي! تقدر تسجل بياناتها، تتابع صياناتها، وتظبط مواعيد تجديد الرخص بسهولة.',
      'start_now': 'ابدأ الان',

// للكلمات اللي ظهرت في الصور التانية (تأكيد على اللي فات)
      'welcome_to_gear_up': 'أهلاً بك في GEAR UP',
      'skip': 'تخطي',
      'q1_title': 'هل تمتلك سيارة حالياً؟',
      // أزرار عامة وتنبيهات
      'enter_app': 'دخول التطبيق',

// الشاشة الترحيبية
      'welcome_to': 'أهلاً بك في',
      'gear_up': ' GEAR UP',
      'app_subtitle': 'تطبيق السيارات الأول المدعوم بالذكاء الاصطناعي',
      'feature_1': 'مساعد ذكي للرد على استفساراتك',
      'feature_2': 'ترشيحات سيارات متفصلة على مقاسك',
      'feature_3': 'تحليل أسعار ومواصفات دقيقة',
      'start_customization': 'يلا نبدأ التخصيص',

// السؤال الأول
      'question_1': 'السؤال الأول',
      'q1_ans_yes': 'نعم، أمتلك سيارة',
      'q1_ans_no': 'لا، أبحث عن سيارة',

// السؤال الثاني
      'question_2': 'السؤال الثاني',
      'q2_title': 'ما هو الغرض الأساسي من السيارة؟',
      'q2_ans_family': 'عائلية ومريحة',
      'q2_ans_economy': 'اقتصادية للعمل واليومي',
      'q2_ans_sport': 'شبابية ورياضية',
      'q2_ans_luxury': 'فخامة ورفاهية',

// السؤال الأخير
      'question_last': 'السؤال الأخير',
      'q3_title': 'ما هي ميزانيتك التقريبية؟',
      'q3_ans_1': 'أقل من 500 ألف ج.م',
      'q3_ans_2': 'من 500 ألف إلى مليون ج.م',
      'q3_ans_3': 'من مليون إلى 2 مليون ج.م',
      'q3_ans_4': 'أكثر من 2 مليون ج.م',

// الشاشة النهائية
      'customizing_ai': 'جاري تخصيص التطبيق لك بالذكاء الاصطناعي...',
      'ready_to_go': 'جاهزين للانطلاق! 🚀',
      'prefs_saved_desc': 'تم حفظ تفضيلاتك بنجاح، دلوقتي هتشوف العربيات اللي متفصلة على مقاسك بالظبط في الصفحة الرئيسية.',

// ميزة سيارتي (التوتوريال)
      'welcome_title': 'أهلاً بك في GEAR UP',
      'welcome_subtitle': 'تطبيق السيارات الأول المدعوم بالذكاء الاصطناعي',
      'start_customization_btn': 'يلا نبدأ التخصيص',
      "saved_parts": "القطع المحفوظة",
      "compatibility": "متوافق مع",
      "fits": "يناسب:",
      "type_part": "قطعة غيار",
      "share_part_text": "🚗 لقيت قطعة الغيار دي على Gear Up!\n\n✨ القطعة: ",
      "search_in": "ابحث في",
      "no_rated_cars_yet": "لم يتم تقييم سيارات حتى الآن",
      "no_matching_cars_found": "لا توجد سيارات مطابقة للبحث",
      "no_news_available": "لا توجد أخبار متاحة",
      "recent_searches": "آخر عمليات البحث",
      "start_searching": "ابحث عن سيارتك المفضلة الآن...",
      'no_reviews_yet': 'لا توجد تقييمات حتى الآن. كن أول من يقيم!',
      'search_cars': 'ابحث عن سيارات...',
      "apply_filters": "تطبيق الفلاتر",
      "clear_all": "مسح الكل",
      "filtered_results": "نتائج الفلتر",
      "clear_filter": "إلغاء الفلتر",
      "brands": "الماركات",
      "max_price": "أقصى سعر",
      "all_brands": "كل الماركات",
      "up_to": "حتى",
      "curated_for_you": "تشكيلة مختارة لك",
      "randomly_selected_for_you": "تم فرزها عشوائياً خصيصاً لك",
      "latest_cars_news": "أحدث أخبار السيارات",
      "news_insights": "أخبار وتحليلات",
      "no_news_to_show": "لا توجد أخبار متاحة حالياً",
      "explore_premium_selection": "اكتشف تشكيلتنا المميزة",
      "click_to_read_more": "اضغط لقراءة التفاصيل كاملة...",
      "chat_history": "سجل المحادثات",
      "new_chat": "محادثة جديدة",
      "no_previous_chats": "لا يوجد محادثات سابقة",
      "rename_chat": "تغيير الاسم",
      "copy_chat": "نسخ المحادثة",
      "share_chat": "مشاركة المحادثة",
      "delete_chat": "مسح المحادثة",
      "edit": "تعديل",
      "ai_thinking": "الذكاء الاصطناعي يفكر...",
      "always_here_to_help": "دائماً هنا للمساعدة",
      "rename_chat_title": "تغيير اسم المحادثة",
      "type_new_name": "اكتب الاسم الجديد...",
      "cancel": "إلغاء",
      "save": "حفظ",
      "delete_confirmation_title": "تأكيد الحذف",
      "delete_confirmation_desc": "هل أنت متأكد أنك تريد مسح هذه المحادثة نهائياً؟",
      "yes_delete": "نعم، امسح",
      "chat_deleted_success": "تم مسح المحادثة بنجاح",
      "chat_copied_success": "تم نسخ المحادثة بنجاح!",
      "share_header": "🤖 محادثة من GEAR UP AI:\n\n",
      "you": "👤 أنت",
      "assistant": "🤖 المساعد",
      "connection_error": "حدث خطأ في الاتصال، يرجى التأكد من جودة الإنترنت.",
      'start_ad_now': 'ابدأ إعلانك الآن',
      'no_parts_to_show': 'لا توجد قطع غيار للعرض حالياً',
      'recently_added': 'المضاف حديثاً',
      'promoted_parts': 'قطع غيار مميزة',
      'seller_location_title': 'عنوان المعرض',
      'open_in_maps': 'افتح في خرائط جوجل',
      'seller_info': 'بيانات البائع',
      'seller_name': 'اسم البائع (اختياري)',
      'seller_phone': 'رقم الهاتف (إجباري)',
      'seller_email': 'البريد الإلكتروني (اختياري)',
      'seller_location': 'مكان المعرض (اختياري)',
      'phone_required_error': 'رقم الهاتف مطلوب لنشر الإعلان',
      'top_rated_cars': 'السيارات الأعلى تقييماً',
      'no_cars_to_show': 'لا توجد سيارات للعرض حالياً',
      'new_user': 'مستخدم جديد',
      'fetching_location': 'جاري تحديد الموقع...',
      'version': 'تطبيق GEAR UP إصدار 2.0.0',
      'copyright': '© 2026 GEAR UP. جميع الحقوق محفوظة.',

      // ================= Start Selling =================
      'start_selling_title': 'ابدأ البيع',
      'choose_item_type': 'اختر نوع العنصر وأضف التفاصيل',
      'change': 'تغيير',
      'photos': 'الصور',
      'add_photo': 'إضافة صورة',
      'photo_hint': '0/10 صور - أضف صوراً واضحة من زوايا مختلفة',
      'photo_limit_hint': 'تقدر تضيف لحد 10 صور للعربية (اختياري)',
      'title': 'العنوان',
      'title_hint': 'أدخل عنواناً جذاباً',
      'price_egp': 'السعر (ج.م)',
      'price_hint': 'أدخل السعر',
      'transmission_hint': 'اختر النوع',
      'part_name': 'اسم القطعة/الإكسسوار',
      'part_hint': 'مثال: تيل فرامل سيراميك',
      'compat_hint': 'مثال: BMW X5 2020-2024',
      'condition_hint': 'اختر الحالة',
      'description': 'الوصف',
      'desc_hint': 'أضف وصفاً تفصيلياً...',
      'desc_optional_hint': 'اكتب وصف للعربية (اختياري)',
      'publish_listing': 'نشر الإعلان',
      'select_item_type': 'اختر نوع العنصر',
      'type_car': 'سيارة',
      'type_accessory': 'إكسسوار',
      'new_condition': 'جديد',
      'used_condition': 'مستعمل',
      'refurbished': 'مجدد',
      'company_hint': 'مثال: BMW',
      'model_hint': 'مثال: X5',
      'year_optional_hint': '2024 (اختياري)',
      'mileage_optional_hint': 'كم (اختياري)',
      'hp_optional_hint': '335 (اختياري)',
      'cc_optional_hint': '3000 (اختياري)',
      'torque_optional_hint': '330 (اختياري)',
      'luggage_optional_hint': '650 لتر (اختياري)',
      'price_make_required': 'السعر والماركة مطلوبين على الأقل',
      'not_specified': 'غير محدد',
      'publish_success': 'تم نشر إعلانك بنجاح!',
      'coming_soon_parts': 'إضافة قطع الغيار سيتم تفعيلها قريباً',

      // ================= Privacy Policy =================
      'privacy_policy_title': 'سياسة الخصوصية',
      'last_updated': 'آخر تحديث: 23 أكتوبر 2025',
      'pp_sec1_title': '1. المعلومات التي نجمعها',
      'pp_sec1_p1': 'تقوم GEAR UP بجمع المعلومات التي تقدمها لنا مباشرة عند إنشاء حساب، أو استخدام خدماتنا، أو التواصل معنا. قد يشمل ذلك اسمك وعنوان بريدك الإلكتروني ورقم هاتفك ومعلومات سيارتك.',
      'pp_sec1_p2': 'نقوم أيضاً تلقائياً بجمع معلومات معينة حول جهازك وكيفية تفاعلك مع تطبيقنا، بما في ذلك عنوان IP الخاص بك، ونوع الجهاز، ونظام التشغيل، وأنماط الاستخدام.',
      'pp_sec2_title': '2. كيف نستخدم معلوماتك',
      'pp_sec2_p1': 'نستخدم المعلومات التي نجمعها من أجل:',
      'pp_sec2_b1': 'توفير خدماتنا وصيانتها وتحسينها',
      'pp_sec2_b2': 'إرسال إشعارات فنية ورسائل دعم',
      'pp_sec2_b3': 'الرد على تعليقاتك وأسئلتك',
      'pp_sec2_b4': 'تقديم توصيات سيارات مخصصة',
      'pp_sec2_b5': 'مراقبة وتحليل الاتجاهات والاستخدام والأنشطة',
      'pp_sec2_b6': 'اكتشاف المشكلات الفنية ومنعها ومعالجتها',
      'pp_sec3_title': '3. مشاركة المعلومات',
      'pp_sec3_p1': 'نحن لا نبيع معلوماتك الشخصية. قد نشارك معلوماتك فقط في الحالات التالية: بموافقتك، مع مقدمي الخدمات الذين يساعدوننا في إدارة أعمالنا، للامتثال للالتزامات القانونية، أو لحماية حقوقنا وسلامتنا.',
      'pp_sec4_title': '4. أمن البيانات',
      'pp_sec4_p1': 'نتخذ تدابير معقولة للمساعدة في حماية معلوماتك الشخصية من الفقدان والسرقة وسوء الاستخدام والوصول غير المصرح به والإفصاح والتعديل والإتلاف. ومع ذلك، لا يوجد نقل عبر الإنترنت آمن تماماً أو خالٍ من الأخطاء.',
      'pp_sec5_title': '5. حقوقك وخياراتك',
      'pp_sec5_p1': 'لديك الحق في:',
      'pp_sec5_b1': 'الوصول إلى معلومات حسابك وتحديثها',
      'pp_sec5_b2': 'طلب حذف بياناتك الشخصية',
      'pp_sec5_b3': 'إلغاء الاشتراك في المراسلات التسويقية',
      'pp_sec5_b4': 'تعطيل ملفات تعريف الارتباط من خلال إعدادات المتصفح',
      'pp_sec6_title': '6. خصوصية الأطفال',
      'pp_sec6_p1': 'خدماتنا غير موجهة للأطفال دون سن 13 عاماً. نحن لا نجمع عن قصد معلومات شخصية من الأطفال دون سن 13. إذا علمت أن طفلاً قد زودنا بمعلومات شخصية، يرجى الاتصال بنا.',
      'pp_sec7_title': '7. التغييرات على هذه السياسة',
      'pp_sec7_p1': 'قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. سنقوم بإعلامك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة وتحديث تاريخ "آخر تحديث".',
      'pp_sec8_title': '8. اتصل بنا',
      'pp_sec8_p1': 'إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يرجى الاتصال بنا على:\nالبريد الإلكتروني: privacy@gearup.com\nالهاتف: +20 2 1234 5678',

      // ================= Profile Screen =================
      'my_account': 'حسابي',
      'start_selling': 'ابدأ البيع',
      'list_new_item': 'عرض عنصر جديد للبيع',
      'published_items': 'العناصر المنشورة',
      'manage_listings': 'إدارة إعلاناتك',
      'account_info_sub': 'الاسم، البريد، الهاتف',
      'edit_profile_sub': 'تحديث معلوماتك',
      'manage_payment_methods': 'إدارة طرق الدفع',
      'app_section': 'التطبيق',
      'settings_sub': 'التفضيلات، الخصوصية، المساعدة',
      'logout': 'تسجيل الخروج',
      'egypt_car_app': 'تطبيق السيارات رقم 1 في مصر',

      // ================= Published Items =================
      'tab_all': 'الكل',
      'tab_cars': 'سيارات',
      'tab_parts': 'قطع غيار',
      'tab_accessories': 'إكسسوارات',
      'no_listings_yet': 'لا توجد إعلانات بعد',
      'haven_not_published': 'لم تقم بنشر أي إعلانات حتى الآن',

      // ================= Profile & Account =================
      'account_information': 'معلومات الحساب',
      'view_account_details': 'عرض تفاصيل حسابك',
      'member_since': 'عضو منذ',
      'email_address': 'البريد الإلكتروني',
      'location': 'الموقع',
      'edit_information': 'تعديل المعلومات',
      'update_account_password': 'تحديث كلمة مرور حسابك',
      'update_password': 'تحديث كلمة المرور',
      'edit_profile': 'تعديل الملف الشخصي',
      'change_profile_photo': 'تغيير صورة الملف الشخصي',

      // ================= Nearby Locations =================
      'nearby_locations': 'الأماكن القريبة',
      'service_and_showrooms': 'مراكز صيانة ومعارض سيارات',
      'interactive_map': 'خريطة تفاعلية',
      'shows_places_near_you': 'تعرض مراكز الصيانة والمعارض القريبة منك',
      'service_center': 'مركز صيانة',
      'showroom': 'معرض سيارات',
      'km_away': 'كم',
      'get_directions': 'الحصول على الاتجاهات',

      // ================= Parts Screen =================
      'car_parts': 'قطع غيار',
      'parts_available': 'قطع متوفرة',
      'search_parts': 'ابحث عن قطع الغيار...',
      'all_companies': 'كل الشركات',
      'default_sort': 'الافتراضي',

      // ================= General & Navigation =================
      'home': 'الرئيسية',
      'compare': 'مقارنة',
      'parts': 'قطع غيار',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'delete': 'حذف',
      'manage': 'إدارة',

      // ================= Splash & Welcome =================
      'premium_companion': 'رفيقك المتميز للسيارات',
      'skip_to_home': 'تخطي للرئيسية',

      // ================= Auth Screens =================
      'welcome_back': 'مرحباً بعودتك',
      'sign_in': 'سجل الدخول للمتابعة',
      'forgot_password_title': 'هل نسيت كلمة المرور؟',
      'forgot_password_desc': 'أدخل بريدك الإلكتروني وسنرسل لك تعليمات لإعادة تعيين كلمة المرور',
      'email': 'البريد الإلكتروني',
      'email_hint': 'your@email.com',
      'send_reset_link': 'إرسال رابط الاستعادة',
      'back_to_login': 'الرجوع لتسجيل الدخول',
      'password': 'كلمة المرور',
      'password_hint': '••••••••',
      'or_continue_with': 'أو المتابعة باستخدام',
      'google': 'جوجل',
      'facebook': 'فيسبوك',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'sign_up': 'إنشاء حساب',
      'create_account': 'إنشاء حساب جديد',
      'join_gear_up': 'انضم إلى GEAR UP اليوم',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'phone_hint': '+20 123 456 7890',
      'confirm_password': 'تأكيد كلمة المرور',
      'already_have_account': 'لديك حساب بالفعل؟ ',

      // ================= Home & Search =================
      'popular_searches': 'عمليات البحث الشائعة',
      'find_nearby': 'الأماكن القريبة',
      'promoted': 'إعلانات ممولة',
      'featured_listings': 'قوائم مميزة',
      'premium_listings': 'إعلانات مميزة ومدفوعة',
      'top_rated_new': 'سيارات جديدة عالية التقييم',
      'best_rated_2025': 'أفضل السيارات تقييماً في 2025',
      'latest_updates': 'أحدث أخبار السيارات',
      'new_cars': 'سيارات جديدة',
      'latest_models': 'أحدث الموديلات من أشهر العلامات',
      'used_cars': 'سيارات مستعملة',
      'quality_preowned': 'سيارات مستعملة بجودة عالية',

      // ================= Compare & Car Details =================
      'specification': 'المواصفة',
      'company': 'الشركة',
      'model': 'الموديل',
      'gear_shifts': 'عدد النقلات',
      'max_speed': 'السرعة القصوى',
      'comparison_guide': 'دليل المقارنة',
      'indicates_advantage': 'يشير إلى ميزة (أفضل)',
      'indicates_disadvantage': 'يشير إلى عيب (أقل)',
      'specifications_title': 'المواصفات',
      'about_vehicle': 'عن هذه السيارة',
      'added_to_comparison': 'تمت الإضافة للمقارنة',
      'total_views': 'إجمالي المشاهدات',
      'reviews': 'التقييمات',
      'top_rated': 'الأعلى تقييماً',
      'mock_desc': 'هي سيارة فاخرة تتميز بمحرك قوي بقوة 335 حصان وسعة 3000 سي سي. مع ناقل حركة أوتوماتيكي و 8 نقلات، تقدم هذه السيارة أداءً وكفاءة استثنائية. يمكن للسيارة الوصول لسرعة قصوى تبلغ 250 كم/ساعة وتوفر سعة أمتعة 650 لتر، مما يجعلها مثالية للتنقلات اليومية والرحلات الطويلة.',

      // ================= My Car & Reminders =================
      'login_signup_msg': 'سجل الدخول أو أنشئ حساباً لإدارة سيارتك، وتتبع سجل الصيانة، وتعيين التذكيرات',
      'manage_vehicles': 'إدارة سياراتك',
      'my_vehicle': 'سيارتي',
      'service_centers': 'مراكز الصيانة',
      'parts_used_notes': 'القطع المستخدمة، ملاحظات الميكانيكي...',
      'edit_my_vehicle': 'تعديل سيارتي',
      'vehicle_details': 'تفاصيل السيارة',
      'update_car_info': 'قم بتحديث معلومات سيارتك والمسافة المقطوعة',
      'change_vehicle_photo': 'تغيير صورة السيارة',
      'car_brand': 'ماركة السيارة',
      'car_model': 'موديل السيارة',
      'manufacturing_year': 'سنة الصنع',
      'mileage_km': 'المسافة (كم)',
      'manage_reminders': 'إدارة تذكيرات صيانة سيارتك',
      'task_hint': 'مثال: تغيير الزيت، تدوير الإطارات',
      'date_hint': 'يوم/شهر/سنة',
      'additional_details': 'تفاصيل إضافية...',
      'delete_reminder': 'حذف التذكير',
      'reminder_deleted': 'تم حذف التذكير بنجاح!',

      // ================= AI Chat & Filters =================
      'ai_title': 'مساعد GEAR UP',
      'ai_subtitle': 'دائماً هنا للمساعدة',
      'ai_greeting': 'أهلاً بك! أنا مساعدك الذكي. كيف يمكنني مساعدتك اليوم؟',
      'quick_suggestions': 'اقتراحات سريعة:',
      'sugg_electric': 'اعرض لي السيارات الكهربائية',
      'sugg_sedans': 'قارن سيارات السيدان تحت 30 ألف',
      'sugg_suvs': 'أفضل سيارات الدفع الرباعي للعائلات',
      'type_message': 'اكتب رسالتك...',
      'filters': 'الفلاتر',
      'price': 'السعر',
      'high_to_low': 'من الأعلى للأقل',
      'low_to_high': 'من الأقل للأعلى',
      'under_500k': 'أقل من 500 ألف',

      // ================= Settings Screen =================
      'manage_preferences': 'إدارة تفضيلات التطبيق والدعم',
      'app_preferences': 'تفضيلات التطبيق',
      'dark_mode': 'الوضع الليلي',
      'dark_enabled': 'الوضع الليلي مفعل',
      'light_enabled': 'الوضع الفاتح مفعل',
      'push_notifications': 'الإشعارات',
      'receive_updates': 'استلام التحديثات والتذكيرات',
      'language': 'اللغة',
      'select_language': 'اختر لغتك المفضلة',
      'security_privacy': 'الأمان والخصوصية',
      'change_password': 'تغيير كلمة المرور',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_privacy': 'الشروط وقواعد الخصوصية',
      'support_about': 'الدعم وحول التطبيق',
      'help_center': 'مركز المساعدة',
      'get_support': 'الحصول على الدعم والأسئلة الشائعة',
      'analytics': 'التحليلات والأداء',
      'help_improve': 'المساعدة في تحسين التطبيق',

      // ================= Help Center Screen =================
      'search_help': 'ابحث عن المساعدة...',
      'chat_support': 'دعم المحادثة',
      'call_us': 'اتصل بنا',
      'email_us': 'راسلنا',
      'user_guide': 'دليل المستخدم',
      'categories': 'الفئات',
      'all': 'الكل',
      'general': 'عام',
      'features': 'الميزات',
      'service': 'الصيانة',
      'faq': 'الأسئلة الشائعة',
      'still_need_help': 'هل ما زلت بحاجة للمساعدة؟',
      'phone': 'الهاتف',
      'faq_q1': 'كيف أبحث عن سيارة؟',
      'faq_a1': 'يمكنك البحث عن السيارات من خلال تصفح الشاشة الرئيسية أو استخدام شريط البحث في الأعلى.',
      'faq_q2': 'كيف أحفظ سيارة في المفضلة؟',
      'faq_a2': 'اضغط على أيقونة القلب على أي بطاقة سيارة لحفظها في قائمة السيارات المحفوظة.',
      'faq_q3': 'كيف تعمل ميزة المقارنة؟',
      'faq_a3': 'حدد سيارتين بالضغط على أيقونة المقارنة، ثم اذهب لعلامة تبويب المقارنة لرؤيتهما جنباً إلى جنب.',
      'faq_q4': 'هل يمكنني تتبع صيانة سيارتي؟',
      'faq_a4': 'نعم! اذهب إلى حسابك، ثم "سيارتي" لإضافة وتتبع سجل الصيانة الخاص بك.',
      'faq_q5': 'كيف أجد قطع الغيار؟',
      'faq_a5': 'قم بزيارة علامة التبويب "قطع الغيار" لتصفح أو البحث عن قطع معينة.',
      'faq_q6': 'كيف أعيد تعيين كلمة المرور الخاصة بي؟',
      'faq_a6': 'في شاشة تسجيل الدخول، اضغط على "هل نسيت كلمة المرور؟" لاستلام رابط الاستعادة.',
      'faq_q7': 'أين يمكنني إيجاد مراكز صيانة قريبة مني؟',
      'faq_a7': 'اذهب للشاشة الرئيسية واضغط على "الأماكن القريبة" لرؤية خريطة مراكز الصيانة.',
      'faq_q8': 'كيف أفعل الوضع الليلي؟',
      'faq_a8': 'انتقل إلى الإعدادات من حسابك وقم بتفعيل مفتاح الوضع الليلي.',
      'faq_q9': 'ما هو مساعد الذكاء الاصطناعي؟',
      'faq_a9': 'مساعد الذكاء الاصطناعي هو مساعدك الافتراضي. اضغط على الأيقونة العائمة لطرح الأسئلة.',
      'faq_q10': 'كيف أغير معلومات حسابي؟',
      'faq_a10': 'اذهب إلى صفحة حسابك واضغط على "تعديل المعلومات".',
      "tour_start_ad_title": "ابدأ إعلانك",
      "tour_start_ad_desc": "اضغط هنا عشان تنشر إعلان سيارتك وتوصل لآلاف المشترين.",
      "tour_my_car_title": "جراجك الرقمي",
      "tour_my_car_desc": "تابع صيانات ومصاريف سيارتك.",
      "tour_profile_title": "حسابك الشخصي",
      "tour_profile_desc": "كل إعداداتك وإعلاناتك هنا.",
      "continue_with_google": "المتابعة باستخدام Google",
      "or_login_with_email": "أو سجل دخول بالبريد الإلكتروني",
      "siren_channel_desc": "قناة مخصصة لتنبيهات الصيانة بصوت السرينة",
      "nav_home": "الرئيسية",
      "nav_compare": "مقارنة",
      "nav_parts": "قطع غيار",
      "nav_my_car": "سيارتي",
      "nav_profile": "حسابي",

      // ================= Payments Screen =================
      'payments': 'المدفوعات',
      'manage_payments': 'إدارة المدفوعات',
      'payment_methods': 'طرق الدفع',
      'history': 'السجل',
      'add_payment_method': 'إضافة طريقة دفع',
      'default_method': 'الافتراضي',
      'select_payment_method': 'اختر طريقة الدفع',
      'credit_debit_card': 'بطاقة ائتمان / خصم',
      'add_card': 'إضافة بطاقة',
      'add_instapay': 'إضافة إنستاباي',
      'add_vodafone_cash': 'إضافة فودافون كاش',
      'cardholder_name': 'اسم صاحب البطاقة',
      'cvv': 'الرقم السري (CVV)',
      'name': 'الاسم',
      'completed': 'مكتمل',
      'pending': 'قيد الانتظار',
      "sugg_title_1": "أحدث أخبار السيارات",
      "sugg_desc_1": "إيه الجديد في سوق السيارات في مصر؟",
      "sugg_title_2": "أعطال ومشاكل",
      "sugg_desc_2": "عربيتي بتسخن بسرعة، إيه السبب؟",
      "sugg_title_3": "نصائح قبل الشراء",
      "sugg_desc_3": "إزاي أفحص عربية مستعملة قبل ما أشتريها؟",
      "sugg_title_4": "مقارنة سيارات",
      "sugg_desc_4": "إيه أفضل عربية عائلية في حدود مليون جنيه؟",
      'top_rated_badge': 'الأعلى تقييماً',
      "location_services_disabled": "يرجى تفعيل خدمة الموقع (GPS)",
      "location_permission_denied": "تم رفض صلاحية الموقع",
      "location_permission_permanently_denied": "تم رفض الصلاحية من إعدادات الهاتف",
      "current_location": "موقعك الحالي",
      "cannot_open_maps": "لا يمكن فتح الخرائط",
      "no_data_currently": "لا توجد بيانات حالياً",
      "km_label": "كم",
      "meter_label": "متر",
  "remove_from_compare": "إزالة من المقارنة",
  "manage_reviews_reports": "مراجعة التعليقات",
  "review_reported_comments_desc": "مراجعة وحذف التعليقات التي تحتوي على إساءة",
  "reported_reviews_title": "مراجعة التعليقات",
  "no_reported_reviews": "لا توجد بلاغات معلقة!",
  "reported_reviews_count": "تعليقات مسيئة",
      "or_sign_up_with_email": "أو سجل بالبريد الإلكتروني",
      "open_mail_app": "فتح تطبيق الإيميل",
      "check_spam_hint": "لو مش لاقي الإيميل، فتش في مجلد الـ Spam أو Junk",
      "no_email_app": "لم يتم العثور على تطبيق بريد إلكتروني بهاتفك.",
      "choose_email_app": "اختر تطبيق البريد"
}
  };

  static String tr(BuildContext context, String key) {
    Locale locale = Localizations.localeOf(context);
    return _translations[locale.languageCode]?[key] ?? key;
  }
}